# Generated by Django 4.2.20 on 2025-10-27 14:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Employee's first name", max_length=100)),
                ('full_name', models.CharField(help_text="Employee's full name", max_length=200)),
                ('contact', models.CharField(help_text="Employee's contact number", max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('email', models.EmailField(help_text="Employee's email address", max_length=254, unique=True)),
                ('aadhar_card_number', models.CharField(help_text="Employee's Aadhar card number", max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Aadhar number must be exactly 12 digits.')])),
                ('account_number', models.CharField(help_text="Employee's bank account number", max_length=20, validators=[django.core.validators.RegexValidator('^\\d{9,18}$', 'Account number must be 9-18 digits.')])),
                ('ifsc_code', models.CharField(help_text='Bank IFSC code', max_length=11, validators=[django.core.validators.RegexValidator('^[A-Z]{4}0[A-Z0-9]{6}$', 'Enter a valid IFSC code.')])),
                ('pan_card', models.CharField(help_text="Employee's PAN card number", max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z]{5}[0-9]{4}[A-Z]{1}$', 'Enter a valid PAN card number.')])),
                ('profile_picture', models.ImageField(blank=True, help_text="Employee's profile picture", null=True, upload_to='profile_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Associated Django user account', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['name', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True, help_text='Timestamp when employee checked in')),
                ('date', models.DateField(auto_now_add=True, help_text='Date of the check-in')),
                ('employee', models.ForeignKey(help_text='Employee who checked in', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-check_in_time'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
