# Generated by Django 4.2.20 on 2025-10-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(help_text="Employee's email address", max_length=254),
        ),
    ]
