# Generated by Django 4.2.20 on 2025-10-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_attendance_check_in_photo_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='face_encoding',
            field=models.TextField(blank=True, help_text='JSON-encoded face encoding data for recognition', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='face_registered',
            field=models.BooleanField(default=False, help_text='Whether face recognition data has been registered'),
        ),
        migrations.AddField(
            model_name='employee',
            name='face_registered_at',
            field=models.DateTimeField(blank=True, help_text='When face was registered for recognition', null=True),
        ),
    ]
