# Generated by Django 4.2.20 on 2025-10-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_face_encoding_employee_face_registered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(help_text='Date of the check-in'),
        ),
    ]
