# Generated by Django 4.2.20 on 2025-10-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_out_photo',
            field=models.ImageField(blank=True, help_text='Photo taken during check-out for verification', null=True, upload_to='checkout_photos/'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp when employee checked out', null=True),
        ),
    ]
