# Generated by Django 4.2.20 on 2025-10-28 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_attendance_check_out_photo_attendance_check_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='current_address',
            field=models.TextField(blank=True, help_text='Current residential address', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_address',
            field=models.TextField(blank=True, help_text='Permanent residential address', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='relation_with_employee',
            field=models.CharField(blank=True, help_text='Relationship with the employee (e.g., Father, Mother, Spouse)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='relative_contact',
            field=models.CharField(blank=True, help_text='Contact number of the relative', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')]),
        ),
        migrations.AddField(
            model_name='employee',
            name='relative_name',
            field=models.CharField(blank=True, help_text='Name of the relative', max_length=100, null=True),
        ),
    ]
