# Generated by Django 4.2.20 on 2025-10-28 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_current_address_employee_permanent_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_type', models.CharField(choices=[('check_in', 'Check-in'), ('check_out', 'Check-out'), ('face_register', 'Face Registration')], max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, help_text='Employee account associated with the attempt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_attempt_logs', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Face Verification Log',
                'verbose_name_plural': 'Face Verification Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
