# Generated by Django 4.2.20 on 2025-10-28 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0009_attendancelog_delete_faceverificationlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, help_text='Auto-generated ticket number', max_length=20, unique=True)),
                ('subject', models.CharField(help_text='Brief subject of the issue', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('category', models.CharField(choices=[('attendance', 'Attendance Issue'), ('leave', 'Leave Request'), ('payroll', 'Payroll Issue'), ('technical', 'Technical Support'), ('hr', 'HR Related'), ('facility', 'Facility/Infrastructure'), ('other', 'Other')], default='other', help_text='Category of the ticket', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='open', help_text='Current status', max_length=15)),
                ('attachment', models.FileField(blank=True, help_text='Optional file attachment', null=True, upload_to='ticket_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the ticket was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the ticket was resolved', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes by admin', null=True)),
                ('employee', models.ForeignKey(help_text='Employee who raised the ticket', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='employees.employee')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Admin who resolved the ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Comment text')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal note (visible only to admins)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the comment was posted')),
                ('ticket', models.ForeignKey(help_text='Related ticket', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='employees.ticket')),
                ('user', models.ForeignKey(help_text='User who posted the comment', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket Comment',
                'verbose_name_plural': 'Ticket Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['-created_at'], name='employees_t_created_009c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['employee', '-created_at'], name='employees_t_employe_d0e81d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', '-created_at'], name='employees_t_status_475fd5_idx'),
        ),
    ]
