# Generated by Django 4.2.20 on 2025-10-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_ticket_ticketcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude of check-in location', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude of check-in location', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude of check-out location', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude of check-out location', max_digits=10, null=True),
        ),
    ]
