# Generated by Django 4.2.20 on 2025-10-29 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0011_attendance_check_in_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address used for request', max_length=254)),
                ('reason', models.TextField(blank=True, help_text='Reason for password reset request', max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Status of the request', max_length=20)),
                ('new_password', models.CharField(blank=True, help_text='New password set by admin (temporary)', max_length=128, null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the request was processed', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about the request', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Employee requesting password reset', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to='employees.employee')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin who processed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_password_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Request',
                'verbose_name_plural': 'Password Reset Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
