# Generated by Django 4.2.20 on 2025-10-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='half_day',
            field=models.BooleanField(default=False, help_text='Whether the attendance is marked as half-day due to early checkout'),
        ),
    ]
